services:
  django:
    build:
      context: ..
      dockerfile: ./myproject/Dockerfile
    container_name: django-app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - ..:/app
    working_dir: /app/myproject
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14.8-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "simplepass123"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  postgres_data:
